/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorytellerRouteRouteImport } from './routes/storyteller/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorytellerIndexRouteImport } from './routes/storyteller/index'
import { Route as StorytellerGrimoireRouteImport } from './routes/storyteller/grimoire'
import { Route as StorytellerCharacterSelectRouteImport } from './routes/storyteller/character-select'
import { Route as PlayerLobbyIdRouteImport } from './routes/player.$lobbyId'

const StorytellerRouteRoute = StorytellerRouteRouteImport.update({
  id: '/storyteller',
  path: '/storyteller',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorytellerIndexRoute = StorytellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorytellerRouteRoute,
} as any)
const StorytellerGrimoireRoute = StorytellerGrimoireRouteImport.update({
  id: '/grimoire',
  path: '/grimoire',
  getParentRoute: () => StorytellerRouteRoute,
} as any)
const StorytellerCharacterSelectRoute =
  StorytellerCharacterSelectRouteImport.update({
    id: '/character-select',
    path: '/character-select',
    getParentRoute: () => StorytellerRouteRoute,
  } as any)
const PlayerLobbyIdRoute = PlayerLobbyIdRouteImport.update({
  id: '/player/$lobbyId',
  path: '/player/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/storyteller': typeof StorytellerRouteRouteWithChildren
  '/player/$lobbyId': typeof PlayerLobbyIdRoute
  '/storyteller/character-select': typeof StorytellerCharacterSelectRoute
  '/storyteller/grimoire': typeof StorytellerGrimoireRoute
  '/storyteller/': typeof StorytellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player/$lobbyId': typeof PlayerLobbyIdRoute
  '/storyteller/character-select': typeof StorytellerCharacterSelectRoute
  '/storyteller/grimoire': typeof StorytellerGrimoireRoute
  '/storyteller': typeof StorytellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/storyteller': typeof StorytellerRouteRouteWithChildren
  '/player/$lobbyId': typeof PlayerLobbyIdRoute
  '/storyteller/character-select': typeof StorytellerCharacterSelectRoute
  '/storyteller/grimoire': typeof StorytellerGrimoireRoute
  '/storyteller/': typeof StorytellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/storyteller'
    | '/player/$lobbyId'
    | '/storyteller/character-select'
    | '/storyteller/grimoire'
    | '/storyteller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/player/$lobbyId'
    | '/storyteller/character-select'
    | '/storyteller/grimoire'
    | '/storyteller'
  id:
    | '__root__'
    | '/'
    | '/storyteller'
    | '/player/$lobbyId'
    | '/storyteller/character-select'
    | '/storyteller/grimoire'
    | '/storyteller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StorytellerRouteRoute: typeof StorytellerRouteRouteWithChildren
  PlayerLobbyIdRoute: typeof PlayerLobbyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storyteller': {
      id: '/storyteller'
      path: '/storyteller'
      fullPath: '/storyteller'
      preLoaderRoute: typeof StorytellerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyteller/': {
      id: '/storyteller/'
      path: '/'
      fullPath: '/storyteller/'
      preLoaderRoute: typeof StorytellerIndexRouteImport
      parentRoute: typeof StorytellerRouteRoute
    }
    '/storyteller/grimoire': {
      id: '/storyteller/grimoire'
      path: '/grimoire'
      fullPath: '/storyteller/grimoire'
      preLoaderRoute: typeof StorytellerGrimoireRouteImport
      parentRoute: typeof StorytellerRouteRoute
    }
    '/storyteller/character-select': {
      id: '/storyteller/character-select'
      path: '/character-select'
      fullPath: '/storyteller/character-select'
      preLoaderRoute: typeof StorytellerCharacterSelectRouteImport
      parentRoute: typeof StorytellerRouteRoute
    }
    '/player/$lobbyId': {
      id: '/player/$lobbyId'
      path: '/player/$lobbyId'
      fullPath: '/player/$lobbyId'
      preLoaderRoute: typeof PlayerLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StorytellerRouteRouteChildren {
  StorytellerCharacterSelectRoute: typeof StorytellerCharacterSelectRoute
  StorytellerGrimoireRoute: typeof StorytellerGrimoireRoute
  StorytellerIndexRoute: typeof StorytellerIndexRoute
}

const StorytellerRouteRouteChildren: StorytellerRouteRouteChildren = {
  StorytellerCharacterSelectRoute: StorytellerCharacterSelectRoute,
  StorytellerGrimoireRoute: StorytellerGrimoireRoute,
  StorytellerIndexRoute: StorytellerIndexRoute,
}

const StorytellerRouteRouteWithChildren =
  StorytellerRouteRoute._addFileChildren(StorytellerRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StorytellerRouteRoute: StorytellerRouteRouteWithChildren,
  PlayerLobbyIdRoute: PlayerLobbyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
